"""add created_at in Splits Tables

Revision ID: 3a822de4d093
Revises: 37fa10d532d3
Create Date: 2026-09-13 11:23:10.669743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a822de4d093'
down_revision: Union[str, Sequence[str], None] = '37fa10d532d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('split_day_exercises', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('split_days', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('split_days', 'created_at')
    op.drop_column('split_day_exercises', 'created_at')
    # ### end Alembic commands ###
