"""add type to splits

Revision ID: 442437ef9b32
Revises: a5ed12e4a429
Create Date: 2026-09-15 13:54:26.766213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442437ef9b32'
down_revision: Union[str, Sequence[str], None] = 'a5ed12e4a429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('splits', sa.Column('type', sa.String(), server_default='custom', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('splits', 'type')
    # ### end Alembic commands ###
