"""add SplitDay table and connected it to Split table and established a relationship between them

Revision ID: 74cbe850b661
Revises: 40f7c2810adc
Create Date: 2026-09-12 23:50:06.630740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cbe850b661'
down_revision: Union[str, Sequence[str], None] = '40f7c2810adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('splitDays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['split_id'], ['splits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('splitDays')
    # ### end Alembic commands ###
