"""add Exercise table

Revision ID: cc67b0ec20e4
Revises: a4d5cf8ca331
Create Date: 2026-09-12 20:18:42.551798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc67b0ec20e4'
down_revision: Union[str, Sequence[str], None] = 'a4d5cf8ca331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_muscle', sa.String(), nullable=False),
    sa.Column('secondary_muscle', sa.String(), nullable=True),
    sa.Column('joint_action', sa.String(), nullable=True),
    sa.Column('movement_pattern', sa.String(), nullable=False),
    sa.Column('type', sa.String(), server_default='custom', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
