"""add notes to Exercise table

Revision ID: e53e134fc37a
Revises: cc67b0ec20e4
Create Date: 2026-09-12 21:03:07.413596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53e134fc37a'
down_revision: Union[str, Sequence[str], None] = 'cc67b0ec20e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'notes')
    # ### end Alembic commands ###
